# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: COGNEX Korea GS&S Blog
subtitle: "Work Hard, Play Hard, Move Fast"
email: info.kr@cognex.com
name: Cognex Korea
description: >
  Work Hard, Play Hard, Move Fast
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/gss-wiki" # the subpath of your site, e.g. /blog/
url: "http://cognex.com" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: deep-learning
    desc: "Posts describing Cognex Deep Learning Solution."

  - cat: base product
    desc: "Posts describing Cognex Base Product Solution."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: Cognex
    url: https://twitter.com/cognex_corp
    desc: Follow us on Twitter
    share: false

  - name: Facebook
    icon: facebook
    username: Cognex
    url: https://ko-kr.facebook.com/cognexcorp
    desc: Friend me on Facebook
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Cognex
    url: https://kr.linkedin.com/company/cognex-corporation
    desc: Connect with me on LinkedIn
    share: false

  - name: Google+
    icon: google-plus
    username: Cognex
    url: https://plus.google.com/110947668324922031522
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username: Cognex
    url: https://www.youtube.com/user/CognexTV
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: Cognex
    url: https://www.instagram.com/explore/locations/38470780/cognex/
    desc: Follow me on Instagram
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
